const noteModel = {
    notes: [
        {
            ID: 1,
            content: 'Social',
            aboutColor: 'red',
            group: 'red 1',
            redAgree: 3,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 521,
            posY: 275,
            zIndex: 1,
        },
        {
            ID: 2,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'red 1',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 852,
            posY: 654,
            zIndex: 2,
        },
        {
            ID: 3,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'red 1',
            redAgree: 1,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1333,
            posY: 348,
            zIndex: 3,
        },
        {
            ID: 4,
            content: 'Hjelpsom',
            aboutColor: 'red',
            group: 'red 1',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 5,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'green 1',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 435,
            posY: 234,
            zIndex: 1,
        },
        {
            ID: 6,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'green 1',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 273,
            posY: 538,
            zIndex: 2,
        },
        {
            ID: 7,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'green 1',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 919,
            posY: 256,
            zIndex: 3,
        },
        {
            ID: 8,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'green 1',
            greenAgree: 4,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 818,
            posY: 563,
            zIndex: 4,
        },
        {
            ID: 9,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'blue 1',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1349,
            posY: 720,
            zIndex: 1,
        },
        {
            ID: 10,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'blue 1',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 925,
            posY: 722,
            zIndex: 2,
        },
        {
            ID: 11,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'blue 1',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 69,
            posY: 720,
            zIndex: 3,
        },
        {
            ID: 12,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'blue 1',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 511,
            posY: 726,
            zIndex: 4,
        },
        {
            ID: 13,
            content: 'Social',
            aboutColor: 'red',
            group: 'green 1',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 14,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'green 1',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 259,
            posY: 670,
            zIndex: 2,
        },
        {
            ID: 15,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'green 1',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1319,
            posY: 297,
            zIndex: 3,
        },
        {
            ID: 16,
            content: 'Vennlig',
            aboutColor: 'red',
            group: 'green 1',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1292,
            posY: 705,
            zIndex: 4,
        },
        {
            ID: 17,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'blue 1',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1233,
            posY: 480,
            zIndex: 1,
        },
        {
            ID: 18,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'blue 1',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 309,
            posY: 488,
            zIndex: 2,
        },
        {
            ID: 19,
            content: 'drømmende',
            aboutColor: 'green',
            group: 'blue 1',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 772,
            posY: 488,
            zIndex: 3,
        },
        {
            ID: 20,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'blue 1',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 767,
            posY: 703,
            zIndex: 4,
        },
        {
            ID: 21,
            content: 'Målrettet',
            aboutColor: 'blue',
            group: 'red 1',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 427,
            posY: 375,
            zIndex: 1,
        },
        {
            ID: 22,
            content: 'Planerer',
            aboutColor: 'blue',
            group: 'red 1',
            redAgree: 3,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 259,
            posY: 614,
            zIndex: 2,
        },
        {
            ID: 23,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'red 1',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1214,
            posY: 278,
            zIndex: 3,
        },
        {
            ID: 24,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'red 1',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1262,
            posY: 706,
            zIndex: 4,
        },
        {
            ID: 25,
            content: 'Social',
            aboutColor: 'red',
            group: 'blue 1',
            blueAgree: 6,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1322,
            posY: 748,
            zIndex: 1,
        },
        {
            ID: 26,
            content: 'Idealist',
            aboutColor: 'red',
            group: 'blue 1',
            blueAgree: 7,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 912,
            posY: 750,
            zIndex: 2,
        },
        {
            ID: 27,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'blue 1',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 74,
            posY: 747,
            zIndex: 3,
        },
        {
            ID: 28,
            content: 'Vennlig',
            aboutColor: 'red',
            group: 'blue 1',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 502,
            posY: 754,
            zIndex: 4,
        },
        {
            ID: 29,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'red 1',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 135,
            posY: 332,
            zIndex: 1,
        },
        {
            ID: 30,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'red 1',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 374,
            posY: 548,
            zIndex: 2,
        },
        {
            ID: 31,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'red 1',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1137,
            posY: 339,
            zIndex: 3,
        },
        {
            ID: 32,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'red 1',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 801,
            posY: 545,
            zIndex: 4,
        },
        {
            ID: 33,
            content: 'Målrettet',
            aboutColor: 'blue',
            group: 'green 1',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 98,
            posY: 324,
            zIndex: 1,
        },
        {
            ID: 34,
            content: 'Planerer',
            aboutColor: 'blue',
            group: 'green 1',
            greenAgree: 8,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 744,
            posY: 439,
            zIndex: 2,
        },
        {
            ID: 35,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'green 1',
            greenAgree: 2,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1169,
            posY: 679,
            zIndex: 3,
        },
        {
            ID: 36,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'green 1',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 333,
            posY: 744,
            zIndex: 4,
        },
        {
            ID: 37,
            content: 'Social',
            aboutColor: 'red',
            group: 'red 2',
            redAgree: 3,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 589,
            posY: 297,
            zIndex: 1,
        },
        {
            ID: 38,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'red 2',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 488,
            posY: 674,
            zIndex: 2,
        },
        {
            ID: 39,
            content: 'Rådgiver',
            aboutColor: 'red',
            group: 'red 2',
            redAgree: 1,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1168,
            posY: 329,
            zIndex: 3,
        },
        {
            ID: 40,
            content: 'Lederskap',
            aboutColor: 'red',
            group: 'red 2',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1108,
            posY: 676,
            zIndex: 4,
        },
        {
            ID: 41,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'green 2',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 96,
            posY: 301,
            zIndex: 1,
        },
        {
            ID: 42,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'green 2',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 94,
            posY: 501,
            zIndex: 2,
        },
        {
            ID: 43,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'green 2',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 95,
            posY: 105,
            zIndex: 3,
        },
        {
            ID: 44,
            content: 'Veifinner',
            aboutColor: 'green',
            group: 'green 2',
            greenAgree: 4,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 97,
            posY: 705,
            zIndex: 4,
        },
        {
            ID: 45,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'blue 2',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 244,
            posY: 242,
            zIndex: 1,
        },
        {
            ID: 46,
            content: 'Lederskap',
            aboutColor: 'blue',
            group: 'blue 2',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1091,
            posY: 621,
            zIndex: 2,
        },
        {
            ID: 47,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'blue 2',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 663,
            posY: 419,
            zIndex: 3,
        },
        {
            ID: 48,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'blue 2',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 239,
            posY: 613,
            zIndex: 4,
        },
        {
            ID: 49,
            content: 'Social',
            aboutColor: 'red',
            group: 'green 2',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1386,
            posY: 601,
            zIndex: 1,
        },
        {
            ID: 50,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'green 2',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 927,
            posY: 602,
            zIndex: 2,
        },
        {
            ID: 51,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'green 2',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1388,
            posY: 188,
            zIndex: 3,
        },
        {
            ID: 52,
            content: 'Vennlig',
            aboutColor: 'red',
            group: 'green 2',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1382,
            posY: 400,
            zIndex: 4,
        },
        {
            ID: 53,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'blue 2',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 149,
            posY: 207,
            zIndex: 1,
        },
        {
            ID: 54,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'blue 2',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 569,
            posY: 396,
            zIndex: 2,
        },
        {
            ID: 55,
            content: 'drømmende',
            aboutColor: 'green',
            group: 'blue 2',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1454,
            posY: 765,
            zIndex: 3,
        },
        {
            ID: 56,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'blue 2',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1017,
            posY: 583,
            zIndex: 4,
        },
        {
            ID: 57,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'red 2',
            redAgree: 8,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 531,
            posY: 332,
            zIndex: 1,
        },
        {
            ID: 58,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'red 2',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 342,
            posY: 658,
            zIndex: 2,
        },
        {
            ID: 59,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'red 2',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1207,
            posY: 206,
            zIndex: 3,
        },
        {
            ID: 60,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'red 2',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1100,
            posY: 656,
            zIndex: 4,
        },
        {
            ID: 61,
            content: 'Social',
            aboutColor: 'red',
            group: 'blue 2',
            blueAgree: 6,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 39,
            posY: 159,
            zIndex: 1,
        },
        {
            ID: 62,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'blue 2',
            blueAgree: 7,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1458,
            posY: 144,
            zIndex: 2,
        },
        {
            ID: 63,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'blue 2',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 1449,
            posY: 751,
            zIndex: 3,
        },
        {
            ID: 64,
            content: 'Hjelpsom',
            aboutColor: 'red',
            group: 'blue 2',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 21,
            posY: 758,
            zIndex: 4,
        },
        {
            ID: 65,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'red 2',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 434,
            posY: 380,
            zIndex: 1,
        },
        {
            ID: 66,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'red 2',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 149,
            posY: 569,
            zIndex: 2,
        },
        {
            ID: 67,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'red 2',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1060,
            posY: 230,
            zIndex: 3,
        },
        {
            ID: 68,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'red 2',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 777,
            posY: 627,
            zIndex: 4,
        },
        {
            ID: 69,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'green 2',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 281,
            posY: 398,
            zIndex: 1,
        },
        {
            ID: 70,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'green 2',
            greenAgree: 8,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 529,
            posY: 654,
            zIndex: 2,
        },
        {
            ID: 71,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'green 2',
            greenAgree: 2,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1330,
            posY: 336,
            zIndex: 3,
        },
        {
            ID: 72,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'green 2',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 1217,
            posY: 649,
            zIndex: 4,
        },
        {
            ID: 73,
            content: 'Social',
            aboutColor: 'red',
            group: 'red 3',
            redAgree: 3,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 74,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'red 3',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 150,
            posY: 250,
            zIndex: 2,
        },
        {
            ID: 75,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'red 3',
            redAgree: 1,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 100,
            zIndex: 3,
        },
        {
            ID: 76,
            content: 'Hjelpsom',
            aboutColor: 'red',
            group: 'red 3',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 77,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'green 3',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 78,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'green 3',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 79,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'green 3',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 80,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'green 3',
            greenAgree: 4,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 81,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'blue 3',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 82,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'blue 3',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 83,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'blue 3',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 84,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'blue 3',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 85,
            content: 'Social',
            aboutColor: 'red',
            group: 'green 3',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 86,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'green 3',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 87,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'green 3',
            greenAgree: 6,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 88,
            content: 'Vennlig',
            aboutColor: 'red',
            group: 'green 3',
            greenAgree: 1,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 89,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'blue 3',
            blueAgree: 8,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 90,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'blue 3',
            blueAgree: 5,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 91,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'blue 3',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 92,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'blue 3',
            blueAgree: 2,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 93,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'red 3',
            redAgree: 8,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 94,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'red 3',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 95,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'red 3',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 96,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'red 3',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 97,
            content: 'Social',
            aboutColor: 'red',
            group: 'blue 3',
            blueAgree: 6,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 98,
            content: 'Forstående',
            aboutColor: 'red',
            group: 'blue 3',
            blueAgree: 7,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 99,
            content: 'Lyttende',
            aboutColor: 'red',
            group: 'blue 3',
            blueAgree: 3,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 100,
            content: 'Hjelpsom',
            aboutColor: 'red',
            group: 'blue 3',
            blueAgree: 1,
            redAgree: 0,
            greenAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 101,
            content: 'Kreativ',
            aboutColor: 'green',
            group: 'red 3',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 102,
            content: 'Inspirerende',
            aboutColor: 'green',
            group: 'red 3',
            redAgree: 2,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 103,
            content: 'Lederskap',
            aboutColor: 'green',
            group: 'red 3',
            redAgree: 5,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 104,
            content: 'Nytenkende',
            aboutColor: 'green',
            group: 'red 3',
            redAgree: 4,
            greenAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
        {
            ID: 105,
            content: 'Logisk',
            aboutColor: 'blue',
            group: 'green 3',
            greenAgree: 5,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 300,
            zIndex: 1,
        },
        {
            ID: 106,
            content: 'Tenkende',
            aboutColor: 'blue',
            group: 'green 3',
            greenAgree: 8,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 100,
            posY: 500,
            zIndex: 2,
        },
        {
            ID: 107,
            content: 'Systematisk',
            aboutColor: 'blue',
            group: 'green 3',
            greenAgree: 2,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 300,
            zIndex: 3,
        },
        {
            ID: 108,
            content: 'Effektiv',
            aboutColor: 'blue',
            group: 'green 3',
            greenAgree: 3,
            redAgree: 0,
            blueAgree: 0,
            disagree: 0,
            posX: 200,
            posY: 500,
            zIndex: 4,
        },
    ],
};
