model.users = [
    {
        name: 'Mr. Blue',
        color: 'blue',
    },
    {
        name: 'Mr. Green',
        color: 'green',
    },
    {
        name: 'Ms. Red',
        color: 'red',
    },
    {
        name: 'Tom',
        color: 'blue',
    },
    {
        name: 'Jerry',
        color: 'green',
    },
    {
        name: 'Poul',
        color: 'red',
    },
    {
        name: 'Ann',
        color: 'blue',
    },
    {
        name: 'Agnes',
        color: 'green',
    },
    {
        name: 'Charlotte',
        color: 'red',
    },
];
model.groups = [
    {
        name: 'Blue about blue 1',
        color: 'blue',
    },
    {
        name: 'Blue about green 1',
        color: 'blue',
    },
    {
        name: 'Blue about red 1',
        color: 'blue',
    },
    {
        name: 'Blue about blue 2',
        color: 'blue',
    },
    {
        name: 'Blue about green 2',
        color: 'blue',
    },
    {
        name: 'Blue about red 2',
        color: 'blue',
    },
    {
        name: 'Green about green 1',
        color: 'green',
    },
    {
        name: 'Green about blue 1',
        color: 'green',
    },
    {
        name: 'Green about red 1',
        color: 'green',
    },
    {
        name: 'Green about green 2',
        color: 'green',
    },
    {
        name: 'Green about blue 2',
        color: 'green',
    },
    {
        name: 'Green about red 2',
        color: 'green',
    },
    {
        name: 'Red about red 1',
        color: 'red',
    },
    {
        name: 'Red about blue 1',
        color: 'red',
    },
    {
        name: 'Red about green 1',
        color: 'red',
    },
    {
        name: 'Red about red 2',
        color: 'red',
    },
    {
        name: 'Red about blue 2',
        color: 'red',
    },
    {
        name: 'Red about green 2',
        color: 'red',
    },
];
model.notes = [
    {
        ID: 1,
        content: 'Social',
        group: 'Red about red 1',
        agree: ['Ann', 'Mr. Green', 'Agnes', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 2,
        content: 'Forstående',
        group: 'Red about red 1',
        agree: [
            'Tom',
            'Ann',
            'Mr. Green',
            'Jerry',
            'Agnes',
            'Ms. Red',
            'Poul',
            'Charlotte',
        ],
        disagree: [],
        posX: 150,
        posY: 250,
        zIndex: 2,
    },
    {
        ID: 3,
        content: 'Lyttende',
        group: 'Red about red 1',
        agree: ['Mr. Green', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 100,
        zIndex: 3,
    },
    {
        ID: 4,
        content: 'Hjelpsom',
        group: 'Red about red 1',
        agree: ['Ann', 'Mr. Green', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 5,
        content: 'Kreativ',
        group: 'Green about green 1',
        agree: [
            'Tom',
            'Mr. Green',
            'Jerry',
            'Agnes',
            'Ms. Red',
            'Poul',
            'Charlotte',
        ],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 6,
        content: 'Inspirerende',
        group: 'Green about green 1',
        agree: ['Ann', 'Mr. Green', 'Jerry'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 7,
        content: 'Lederskap',
        group: 'Green about green 1',
        agree: ['Tom', 'Jerry', 'Agnes', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 8,
        content: 'Nytenkende',
        group: 'Green about green 1',
        agree: ['Mr. Green', 'Jerry', 'Agnes', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 9,
        content: 'Logisk',
        group: 'Blue about blue 1',
        agree: ['Mr. Blue', 'Tom', 'Jerry', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 10,
        content: 'Tenkende',
        group: 'Blue about blue 1',
        agree: ['Mr. Blue', 'Ann', 'Mr. Green'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 11,
        content: 'Systematisk',
        group: 'Blue about blue 1',
        agree: ['Mr. Blue', 'Tom', 'Ann', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 12,
        content: 'Effektiv',
        group: 'Blue about blue 1',
        agree: ['Mr. Blue', 'Mr. Green', 'Agnes', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 13,
        content: 'Social',
        group: 'Green about red 1',
        agree: ['Mr. Green', 'Agnes', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 14,
        content: 'Forstående',
        group: 'Green about red 1',
        agree: ['Tom', 'Mr. Green', 'Jerry', 'Agnes', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 15,
        content: 'Lyttende',
        group: 'Green about red 1',
        agree: ['Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 16,
        content: 'Vennlig',
        group: 'Green about red 1',
        agree: ['Jerry', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 17,
        content: 'Forstående',
        group: 'Blue about green 1',
        agree: ['Tom', 'Ann', 'Agnes', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 18,
        content: 'Inspirerende',
        group: 'Blue about green 1',
        agree: ['Tom', 'Ann', 'Mr. Blue', 'Mr. Green', 'Agnes', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 19,
        content: 'drømmende',
        group: 'Blue about green 1',
        agree: ['Ann', 'Mr. Blue'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 20,
        content: 'Nytenkende',
        group: 'Blue about green 1',
        agree: ['Ann'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 21,
        content: 'Målrettet',
        group: 'Red about blue 1',
        agree: ['Jerry', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 22,
        content: 'Planerer',
        group: 'Red about blue 1',
        agree: [
            'Tom',
            'Ann',
            'Mr. Blue',
            'Mr. Green',
            'Agnes',
            'Ms. Red',
            'Poul',
            'Charlotte',
        ],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 23,
        content: 'Systematisk',
        group: 'Red about blue 1',
        agree: ['Ann', 'Mr. Blue', 'Mr. Green', 'Agnes', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 24,
        content: 'Effektiv',
        group: 'Red about blue 1',
        agree: ['Tom', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 25,
        content: 'Social',
        group: 'Blue about red 1',
        agree: ['Ann', 'Mr. Blue', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 26,
        content: 'Idealist',
        group: 'Blue about red 1',
        agree: ['Tom', 'Ann', 'Mr. Blue', 'Jerry', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 27,
        content: 'Lyttende',
        group: 'Blue about red 1',
        agree: ['Tom', 'Mr. Blue', 'Mr. Green', 'Agnes', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 28,
        content: 'Vennlig',
        group: 'Blue about red 1',
        agree: ['Ann', 'Mr. Blue'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 29,
        content: 'Kreativ',
        group: 'Red about green 1',
        agree: ['Mr. Green', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 30,
        content: 'Inspirerende',
        group: 'Red about green 1',
        agree: ['Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 31,
        content: 'Lederskap',
        group: 'Red about green 1',
        agree: ['Ann', 'Jerry', 'Agnes', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 32,
        content: 'Nytenkende',
        group: 'Red about green 1',
        agree: ['Agnes', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 33,
        content: 'Målrettet',
        group: 'Green about blue 1',
        agree: ['Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 34,
        content: 'Planerer',
        group: 'Green about blue 1',
        agree: ['Ann', 'Mr. Green', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 35,
        content: 'Systematisk',
        group: 'Green about blue 1',
        agree: [
            'Ann',
            'Mr. Green',
            'Jerry',
            'Agnes',
            'Ms. Red',
            'Poul',
            'Charlotte',
        ],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 36,
        content: 'Effektiv',
        group: 'Green about blue 1',
        agree: ['Tom', 'Mr. Green', 'Jerry', 'Ms. Red'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 37,
        content: 'Social',
        group: 'Red about red 2',
        agree: ['Tom', 'Jerry', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 38,
        content: 'Forstående',
        group: 'Red about red 2',
        agree: ['Mr. Green', 'Jerry', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 39,
        content: 'Rådgiver',
        group: 'Red about red 2',
        agree: ['Tom', 'Mr. Green', 'Ms. Red'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 40,
        content: 'Lederskap',
        group: 'Red about red 2',
        agree: ['Tom', 'Mr. Green', 'Jerry'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 41,
        content: 'Kreativ',
        group: 'Green about green 2',
        agree: ['Ann', 'Jerry', 'Agnes', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 42,
        content: 'Inspirerende',
        group: 'Green about green 2',
        agree: ['Tom', 'Ann', 'Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 43,
        content: 'Lederskap',
        group: 'Green about green 2',
        agree: ['Tom', 'Mr. Green', 'Jerry', 'Agnes', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 44,
        content: 'Veifinner',
        group: 'Green about green 2',
        agree: ['Mr. Green', 'Agnes', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 45,
        content: 'Logisk',
        group: 'Blue about blue 2',
        agree: ['Tom', 'Ann', 'Mr. Blue', 'Agnes', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 46,
        content: 'Lederskap',
        group: 'Blue about blue 2',
        agree: ['Tom', 'Ann', 'Ms. Red'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 47,
        content: 'Systematisk',
        group: 'Blue about blue 2',
        agree: ['Tom', 'Ann', 'Mr. Blue', 'Jerry', 'Ms. Red'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 48,
        content: 'Effektiv',
        group: 'Blue about blue 2',
        agree: ['Tom', 'Ann', 'Mr. Green', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 49,
        content: 'Social',
        group: 'Green about red 2',
        agree: ['Tom', 'Mr. Green', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 50,
        content: 'Forstående',
        group: 'Green about red 2',
        agree: ['Tom', 'Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 51,
        content: 'Lyttende',
        group: 'Green about red 2',
        agree: ['Tom', 'Ann', 'Mr. Green', 'Agnes', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 52,
        content: 'Vennlig',
        group: 'Green about red 2',
        agree: ['Ann', 'Mr. Green', 'Jerry', 'Agnes', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 53,
        content: 'Kreativ',
        group: 'Blue about green 2',
        agree: ['Ann', 'Mr. Green', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 54,
        content: 'Inspirerende',
        group: 'Blue about green 2',
        agree: ['Tom', 'Ann', 'Agnes', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 55,
        content: 'drømmende',
        group: 'Blue about green 2',
        agree: ['Tom', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 56,
        content: 'Nytenkende',
        group: 'Blue about green 2',
        agree: ['Ann', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 57,
        content: 'Logisk',
        group: 'Red about blue 2',
        agree: ['Jerry', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 58,
        content: 'Tenkende',
        group: 'Red about blue 2',
        agree: ['Mr. Blue', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 59,
        content: 'Systematisk',
        group: 'Red about blue 2',
        agree: [
            'Tom',
            'Ann',
            'Mr. Blue',
            'Agnes',
            'Ms. Red',
            'Poul',
            'Charlotte',
        ],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 60,
        content: 'Effektiv',
        group: 'Red about blue 2',
        agree: ['Ann', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 61,
        content: 'Social',
        group: 'Blue about red 2',
        agree: ['Tom', 'Ann', 'Poul'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 62,
        content: 'Forstående',
        group: 'Blue about red 2',
        agree: ['Tom', 'Mr. Green', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 63,
        content: 'Lyttende',
        group: 'Blue about red 2',
        agree: ['Ann', 'Mr. Blue', 'Ms. Red'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 64,
        content: 'Hjelpsom',
        group: 'Blue about red 2',
        agree: ['Ann', 'Mr. Blue', 'Jerry', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 65,
        content: 'Kreativ',
        group: 'Red about green 2',
        agree: ['Ann', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 66,
        content: 'Inspirerende',
        group: 'Red about green 2',
        agree: ['Ann', 'Tom', 'Jerry', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 67,
        content: 'Lederskap',
        group: 'Red about green 2',
        agree: ['Mr. Green', 'Agnes', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 68,
        content: 'Nytenkende',
        group: 'Red about green 2',
        agree: ['Mr. Green', 'Ms. Red', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
    {
        ID: 69,
        content: 'Logisk',
        group: 'Green about blue 2',
        agree: ['Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 300,
        zIndex: 1,
    },
    {
        ID: 70,
        content: 'Tenkende',
        group: 'Green about blue 2',
        agree: ['Mr. Blue', 'Mr. Green', 'Jerry', 'Agnes'],
        disagree: [],
        posX: 100,
        posY: 500,
        zIndex: 2,
    },
    {
        ID: 71,
        content: 'Systematisk',
        group: 'Green about blue 2',
        agree: ['Tom', 'Mr. Green', 'Jerry', 'Agnes', 'Ms. Red', 'Poul'],
        disagree: [],
        posX: 200,
        posY: 300,
        zIndex: 3,
    },
    {
        ID: 72,
        content: 'Effektiv',
        group: 'Green about blue 2',
        agree: ['Tom', 'Mr. Blue', 'Mr. Green', 'Jerry', 'Poul', 'Charlotte'],
        disagree: [],
        posX: 200,
        posY: 500,
        zIndex: 4,
    },
];
